- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      pacman:
        update_cache: yes
        upgrade: yes
    - name: copy KPH details
      copy:
        src: files/KPH.txt
        dest: /home/greg/Documents/KPH.txt
        owner: root
        group: root

    - name: copy YAY details
      copy:
        src: files/YAY-ansible.txt
        dest: /home/greg/Documents/YAY-ansible.txt
        owner: root
        group: root


  tasks:
    - include: tasks/packages.yml
    - include: tasks/timezone.yml
