- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      pacman:
        update_cache: yes
        upgrade: yes
    - name: copy wallpaper file
      copy:
        src: files/KPH_data.odt
        dest: /home/greg/Documents/KPH_data.odt
        owner: root
        group: root

  tasks:
    - include: tasks/packages.yml
