- hosts: localhost
  connection: true
  become: true

  pre-tasks:
    - name: update repositories
      pacman:
        update_cache: yes
        upgrade: yes

  tasks:
    - include: tasks/packages.yml
