- name: install packages
  community.general.pacman:
    name: 
      - gimp
      - mc
      - tmux
      - vlc
      - brave
      - nmap
      - audacity
      - filezilla
      - hexchat
      - libreoffice-fresh
      - git
      - kitty
      - lsd
      - gftp
      - gnome-disk-utility
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - krita
      - MComix
      - Steam
      - gftp
      - Konversation
      - Calibre
      - Dropbox
      - Spotify
      - Whatsapp
    state: present

